version: '3'
services:
  sdk:
    #image: mcr.microsoft.com/dotnet/core/sdk:3.1
    build: .
    volumes: 
        - ./src/:/source
    command: ./bash.sh #tail -f /dev/null   #dotnet watch --project /source run  #
    network_mode: host
    ports: 
      - "5000:5000"
