version: '3'
services:
  sdk:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    volumes: 
        - ./src/:/source
    command: dotnet watch --project source run  #tail -f /dev/null 
    network_mode: host
    ports: 
      - "5000:5000"
