// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet.Models;

namespace aspnetapp.Migrations
{
    [DbContext(typeof(SmartPulseContext))]
    [Migration("20200920211806_user_added3q234")]
    partial class user_added3q234
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("dotnet.Models.Central", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("eic")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("organizationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("organizationId");

                    b.ToTable("Centrals");
                });

            modelBuilder.Entity("dotnet.Models.Organization", b =>
                {
                    b.Property<int>("organizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("organizationETSOCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("organizationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("organizationShortName")
                        .HasColumnType("TEXT");

                    b.Property<int>("organizationStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("organizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("dotnet.Models.SavedGrid", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("header")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("rows")
                        .HasColumnType("TEXT");

                    b.Property<string>("useremail")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("useremail");

                    b.ToTable("SavedGrids");
                });

            modelBuilder.Entity("dotnet.Models.User", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("salt")
                        .HasColumnType("TEXT");

                    b.Property<string>("surname")
                        .HasColumnType("TEXT");

                    b.Property<string>("token")
                        .HasColumnType("TEXT");

                    b.HasKey("email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dotnet.Models.WatchList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("json")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("useremail")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("useremail");

                    b.ToTable("WatchLists");
                });

            modelBuilder.Entity("dotnet.Models.Central", b =>
                {
                    b.HasOne("dotnet.Models.Organization", "organization")
                        .WithMany()
                        .HasForeignKey("organizationId");
                });

            modelBuilder.Entity("dotnet.Models.SavedGrid", b =>
                {
                    b.HasOne("dotnet.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("useremail");
                });

            modelBuilder.Entity("dotnet.Models.WatchList", b =>
                {
                    b.HasOne("dotnet.Models.User", "user")
                        .WithMany("watchLists")
                        .HasForeignKey("useremail");
                });
#pragma warning restore 612, 618
        }
    }
}
