// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet.Models;

namespace aspnetapp.Migrations
{
    [DbContext(typeof(SmartPulseContext))]
    [Migration("20200902231513_user_added11511")]
    partial class user_added11511
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("dotnet.Models.Organization", b =>
                {
                    b.Property<int>("organizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("organizationETSOCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("organizationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("organizationShortName")
                        .HasColumnType("TEXT");

                    b.Property<int>("organizationStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("organizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("dotnet.Models.Portfolio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("useremail")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("useremail");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("dotnet.Models.ProductionDB", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("eic")
                        .HasColumnType("TEXT");

                    b.Property<string>("end")
                        .HasColumnType("TEXT");

                    b.Property<string>("etso")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("portfolioid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("start")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("portfolioid");

                    b.ToTable("ProductionDBs");
                });

            modelBuilder.Entity("dotnet.Models.Station", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("eic")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("organizationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("organizationId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("dotnet.Models.Type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("productiondbid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("type")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("productiondbid");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("dotnet.Models.User", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("salt")
                        .HasColumnType("TEXT");

                    b.Property<string>("surname")
                        .HasColumnType("TEXT");

                    b.Property<string>("token")
                        .HasColumnType("TEXT");

                    b.HasKey("email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dotnet.Models.Portfolio", b =>
                {
                    b.HasOne("dotnet.Models.User", "user")
                        .WithMany("portfolios")
                        .HasForeignKey("useremail");
                });

            modelBuilder.Entity("dotnet.Models.ProductionDB", b =>
                {
                    b.HasOne("dotnet.Models.Portfolio", "portfolio")
                        .WithMany("productions")
                        .HasForeignKey("portfolioid");
                });

            modelBuilder.Entity("dotnet.Models.Station", b =>
                {
                    b.HasOne("dotnet.Models.Organization", "organization")
                        .WithMany()
                        .HasForeignKey("organizationId");
                });

            modelBuilder.Entity("dotnet.Models.Type", b =>
                {
                    b.HasOne("dotnet.Models.ProductionDB", "productiondb")
                        .WithMany("types")
                        .HasForeignKey("productiondbid");
                });
#pragma warning restore 612, 618
        }
    }
}
